### ISSUE TITLE
config file creation

### ISSUE THREAD

**Issue by jlaunay** [kbrazulewicz/squadrats2garmin#1]
Hi, I would like to create a config for France but I do not know what to write in the config file for "id", "familyId", "productId" etc.

**Comment by kbrazulewicz** [comment]
Hi @jlaunay, 
Thank you for the feedback and interest in this project. I'll add more information on the values for those fields in the next week.

Cheers!

**Comment by kbrazulewicz** [comment]
Hi @jlaunay 

I've added the documentation draft for the configuration file in [config/README.md](https://github.com/kbrazulewicz/squadrats2garmin/blob/main/config/README.md). I also added a [basic config](https://github.com/kbrazulewicz/squadrats2garmin/blob/main/config/france.json) for France.

Please let me know if you were able to create the config you need. 

Cheers!

**Comment by jlaunay** [comment]
It works perfectly, thank you very much.
